### ISSUE TITLE
Definition package rand_id_queue_pkg seems to be missing

### ISSUE THREAD

**Issue by rlew-metastability** [pulp-platform/axi#180] opened 2021-08-16 16:15 UTC
The package definition for 'rand_id_queue_pkg' seems to have been omitted from the Git repo.  

Attempting to build axi_test.sv results in an error from line 1189 that states:  "Class or package 'rand_id_queue_pkg' not found."

**Comment by zarubaf** [comment] 2021-08-16 16:58
Duplicate of #120 and #70

**Closed by zarubaf** 2021-08-16 16:58 UTC
